apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: model-serving
subjects:
- kind: ServiceAccount
  name: default   # or a custom ServiceAccount if you prefer
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io