apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: model-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.repository }}/txt2img_backend:{{ .Values.image.tag }}
        env:
        - name: CREDENTIAL_JSON_FILE_NAME
          value: "/app/credentials/namsee_key.json"
        - name: STORAGE_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: txt2img-credentials
              key: STORAGE_BUCKET_NAME
        - name: DATABASE_ENGINE
          valueFrom:
            secretKeyRef:
              name: txt2img-credentials
              key: DATABASE_ENGINE
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: txt2img-credentials
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: txt2img-credentials
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: txt2img-credentials
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: txt2img-credentials
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: txt2img-credentials
              key: DATABASE_PORT
        volumeMounts:
        - name: credentials-volume
          mountPath: /app/credentials
          readOnly: true
      volumes:
      - name: credentials-volume
        secret:
          secretName: txt2img-credentials