apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
  namespace: model-serving
spec:
  type: {{ .Values.service.type }}
  selector:
    app: txt2img-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.service.backendPort }}