apiVersion: v1
kind: ConfigMap
metadata:
  name: txt2img-config
  namespace: model-serving
data:
  CREDENTIAL_JSON_FILE_NAME: "${CREDENTIAL_JSON_FILE_NAME}"
  STORAGE_BUCKET_NAME: "${STORAGE_BUCKET_NAME}"
  SECRET_KEY: "${SECRET_KEY}"
  DATABASE_ENGINE: "${DATABASE_ENGINE}"
  DATABASE_NAME: "${DATABASE_NAME}"
  DATABASE_USER: "${DATABASE_USER}"
  DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
  DATABASE_HOST: "${DATABASE_HOST}"
  DATABASE_PORT: "${DATABASE_PORT}"
  NEXT_PUBLIC_BACKEND_URL: "${NEXT_PUBLIC_BACKEND_URL}"