apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: model-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.image.repository }}/txt2img_frontend:{{ .Values.image.tag }}
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: txt2img-credentials
              key: NEXT_PUBLIC_BACKEND_URL