apiVersion: v1
kind: Secret
metadata:
  name: txt2img-secret
  namespace: model-serving
type: Opaque
data:
  NEXT_PUBLIC_BACKEND_URL: {{ .Values.env.NEXT_PUBLIC_BACKEND_URL | b64enc | quote }}
  {{- if .Values.credentials.envVariables }}
  {{- range $key, $value := .Values.credentials.envVariables | fromJson }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}