- name: Create Compute Engine instances
  hosts: localhost
  tasks:
  - name: Bring up the first instance
    gcp_compute_instance:
      name: cicd-instance
      machine_type: n1-standard-4
      zone: us-central1-b
      project: linen-walker-444306-k9 
      auth_kind: serviceaccount
      service_account_file: ../secrets/namsee_key.json
      disks:
        - auto_delete: true
          boot: true
          initialize_params:
            source_image: projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230727
            disk_size_gb: 50
      network_interfaces:
        - network:
            selfLink: global/networks/default
          access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
      state: present

  - name: Create inbound firewall rule for port 8081, 50000, and 9000
    gcp_compute_firewall:
      name: allow-port-8081-50000-9000
      network:
        selfLink: global/networks/default
      allowed:
        - ip_protocol: TCP
          ports:
            - 8081
            - 50000
            - 9000
      source_ranges:
        - 0.0.0.0/0
      direction: INGRESS
      description: Allow incoming traffic on port 8081, 50000, and 9000 (Jenkins and SonarQube)
      project: linen-walker-444306-k9
      auth_kind: serviceaccount
      service_account_file: ../secrets/namsee_key.json